### PR TITLE
feat(attributes-definition): add support for input tips

### LINKED ISSUE #36: Support inputTip for attribute definitions.

### PR DESCRIPTION
**Pull request by PhilippSpo**
Pretty straight foreward
@hajoeichler @emmenko 
closes #36

### CODE REVIEW

**Comment by hajoeichler** [comment]
👍

**Comment by emmenko** [comment]
:+1:

**Comment by emmenko** [comment]
@PhilippSpo what should we do with this PR?

**Comment by PhilippSpo** [comment]
@emmenko wait for #40 to be merged and then merge this one aswell

**Comment by PhilippSpo** [comment]
@junajan can you also take a look at this before we merge it?

**Comment by junajan** [comment]
@PhilippSpo looks good to me 👍

**Pull request merged**
