### PR TITLE
fix(deps): Remove github vulneribility warnings

### PR DESCRIPTION
**Pull request by VineetKumarKushwaha**
### Remove github vulneribility warnings

Fixes: #73

### CODE REVIEW

**Comment by VineetKumarKushwaha** [comment]
@daern91 The tests are failing for node 6(npm 3.10.10) as npx come with npm 5.2+ so I would suggest let's first drop below version of node 8 in the repo and after that we can merge this.
Please let me know your thought on this.

**Comment by daern91** [comment]
Sounds good to me @VineetKumarKushwaha !

**Comment by VineetKumarKushwaha** [comment]
Once https://github.com/sphereio/sphere-product-type-json-generator/issues/75 this issue if fixed will continue on this.

**Comment by VineetKumarKushwaha** [comment]
@daern91 Now you can review these changes.

**Comment by daern91** [comment]
Thanks! Did we also verify that this solution worked in the other packages?

**Comment by VineetKumarKushwaha** [comment]
@daern91 yes I tried install without package-lock.json and yarn.lock and even after releasing I am installing globally to make sure it is working correctly. Though if we get any issue will check.

**Pull request merged**
